config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#home'
  resources :users, only: [:new, :index, :create, :show]
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  namespace :admin do
    resources :categories
  end

  resources :favourites, only: [:create, :destroy]

  resources :gifs, only: [:index, :destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :gifs
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :gif
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  has_many :favourites
  has_many :users, through: :favourites

  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, uniqueness: true, presence: true

  has_many :favourites
  has_many :gifs, through: :favourites

  enum role: %w(default admin)

  def favourite_gif(gif)
    self.gifs << gif
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_user.admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
  end

  def new

  end

  def create
    search_terms = params[:category][:name]
    gif_url = get_gif(search_terms)

    gif = Gif.create(url: gif_url)
    category = Category.find_or_create_by(name: search_terms)
    category.gifs << gif

    redirect_to gifs_path
  end

  def destroy
    category = Category.find(params[:id])
    category.gifs.delete_all
    category.destroy

    redirect_to gifs_path
  end

  def get_gif(search_terms)
    api_key = "dc6zaTOxFJmzC"
    search_terms = search_terms.split(" ").join("+")

    connection = Hurley::Client.new "http://api.giphy.com"
    request = "/v1/gifs/search?q=#{search_terms}&api_key=#{api_key}"
    response = connection.get(request)
    body = parse_response(response.body)
    body["data"][0]["images"]["original"]["url"]
  end

  def parse_response(response)
    JSON.parse(response)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def create
    gif = Gif.find(params[:gif])
    current_user.favourite_gif(gif)
    redirect_to gifs_path
  end

  def destroy
    gif = Gif.find(params[:gif])
    current_user.gifs.delete(gif)
    redirect_to gifs_path
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  def index
    @categories = Category.all
  end

  def destroy
    Gif.destroy(params[:id])
    redirect_to gifs_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path @user
    else
      flash[:errors] = "Invalid login"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def show
    @categories = Category.all
    if session[:user_id] != params[:id].to_i
      render file: '/public/404'
    else
      render "show"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.haml
%h1= "#{current_user.username.capitalize}'s Dashboard"

%br
= link_to "Create Gif", new_admin_category_path

app/views/admin/categories/new.html.haml
%h1 Create Gif

= form_for(Category.new, url: admin_categories_path, method: :post) do |f|
  = f.label :name
  = f.text_field :name
  = f.submit "Create Gif"

app/views/gifs/index.html.haml
%h1 All Gifs
%br
- if current_user.admin?
  =link_to("Dashboard", admin_categories_path)

- @categories.each do |category|
  %div{class: "#{category.name}"}
    %h2= "#{category.name.capitalize}"
    %div{class: "delete_#{category.name}"}
      = link_to("Delete", admin_category_path(category), method: :delete)
    - category.gifs.each do |gif|
      .gif
        = image_tag(gif.url)
        - if current_user.gifs.include?(gif)
          = link_to("Unfavourite", favourite_path(Favourite.where(gif_id: gif.id, user_id: current_user.id), gif: gif.id), method: :delete)
        - else
          = link_to("Favourite", favourites_path(gif: gif.id), method: :post)
        |
        - if current_user.admin?
          = link_to("Delete", gif_path(gif), method: :delete)

app/views/home/home.html.haml
%h1 Gif Generator

= link_to "Login", login_path, class: "btn"

= link_to "Register", new_user_path, class: "btn"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Gif Generator</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to("Logout", logout_path, method: :delete) %></li>
            <li><%= link_to("My Favourties", user_path(current_user)) %></li>
          <% else %>
            <li><%= link_to("Login", login_path) %></li>
          <% end %>
          <li><%= link_to("All Gifs", gifs_path) %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/session/new.html.haml
%h1 Login

- flash.each do |type, msg|
  = content_tag :div, msg, class: "flash_#{type}"

= form_for(:session, url: login_path) do |f|
  = f.label :username
  = f.text_field :username
  = f.label :password
  = f.password_field :password
  = f.submit "Login"

app/views/users/new.html.haml
-flash.each do |type, msg|
  =content_tag :div, msg, class: "flash_#{type}"

%h1 Create account:

= form_for(User.new) do |f|
  = f.label :username
  = f.text_field :username
  = f.label :password
  = f.password_field :password
  = f.submit "Create Account"

app/views/users/show.html.haml
%h1= "#{current_user.username}'s Favourites"
%br
- if current_user.admin?
  = link_to "Dashboard", admin_categories_path

- @categories.each do |category|
  %div{class: "#{category.name}"}
    %h2= "#{category.name.capitalize}"
    - category.gifs.each do |gif|
      - if current_user.gifs.include?(gif)
        .gif
          = image_tag(gif.url)